# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User\User: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:User\User
                property: userName

    firewalls:
        main:
            anonymous: ~
            provider: user_provider
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: UserType[userName]
                password_parameter: UserType[plainPassword]
                remember_me: false
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
