# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        user_provider:
            entity:
                class: AppBundle:User\User
                property: userName

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            anonymous: ~
            provider: user_provider
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login
                username_parameter: UserType[userName]
                password_parameter: UserType[plainPassword]
                remember_me: false
            logout:
                path:   /logout
                target: /

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
